version: "3.9"
services:
  phpservice:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    volumes:
      - ./:/app
      - ./entrypoint/start_laravel_dev.sh:/usr/local/bin/docker-php-entrypoint
    tty: true
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
    links:
      - database
    environment:
      - LARAVEL_PORT=${PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PW}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_NAME}
      - DB_CONNECTION=${DB_CONNECTION}
  database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PW}
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT}"
    volumes:
      - ./entrypoint/database:/docker-entrypoint-initdb.d
      - ./app/data:/var/lib/postgresql/data
