insert into airports (id, code_iata, code_icao, country, municipality, name) values (57136, 'WGN', 'ZGSY', 'CN', 'Shaoyang', 'Shaoyang Wugang Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (28431, 'ELD', 'KELD', 'US', 'El Dorado', 'South Arkansas Regional At Goodwin Field');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (21558, 'MSZ', 'FNMO', 'AO', 'Namibe', 'Namibe Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (28744, 'GMU', 'KGMU', 'US', 'Greenville', 'Greenville Downtown Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (57145, 'LHK', 'ZHGH', 'CN', 'Guanghua', 'Guangzhou MR Air Base');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (44225, 'BHA', 'SESV', 'EC', 'BahÃ­a de Caraquez', 'Los Perales Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (56717, 'QRR', 'YWRN', 'AU', 'nan', 'Warren Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (18194, 'XAR', 'DFOY', 'BF', 'Aribinda', 'Aribinda Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (29686, 'COA', 'KO22', 'US', 'Columbia', 'Columbia Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (33072, 'NAP', 'LIRN', 'IT', 'NÃ¡poli', 'Naples International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (33778, 'GKD', 'LT86', 'TR', 'GÃ¶kÃ§eada', 'GÃ¶kÃ§eada Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (31329, 'SDX', 'KSEZ', 'US', 'Sedona', 'Sedona Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (39708, 'PMS', 'OSPR', 'SY', 'Tadmur', 'Palmyra Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (19758, 'SOG', 'ENSG', 'NO', 'Sogndal', 'Sogndal Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (55472, 'CWT', 'YCWR', 'AU', 'nan', 'Cowra Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (32683, 'CDG', 'LFPG', 'FR', 'Paris', 'Charles de Gaulle International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (54396, 'SXT', 'WMAN', 'MY', 'Taman Negara', 'Sungai Tiang Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (38623, 'WIK', 'NZKE', 'NZ', 'nan', 'Waiheke Reeve Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (20866, 'SZK', 'FASZ', 'ZA', 'Skukuza', 'Skukuza Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (32769, 'SXB', 'LFST', 'FR', 'Strasbourg', 'Strasbourg Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (19701, 'HFT', 'ENHF', 'NO', 'Hammerfest', 'Hammerfest Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (10593, 'LNI', 'AK71', 'US', 'Lonely', 'Lonely Air Station');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (23936, 'LLI', 'HALL', 'ET', 'Lalibela', 'Lalibella Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (12295, 'XIQ', 'BGIL', 'GL', 'Ilimanaq', 'Ilimanaq Heliport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (47935, 'QGF', 'SSNG', 'BR', 'Montenegro', 'Montenegro Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (55417, 'ODL', 'YCOD', 'AU', 'Cordillo Downs', 'Cordillo Downs Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (30045, 'PTT', 'KPTT', 'US', 'Pratt', 'Pratt Regional Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (31330, 'SFB', 'KSFB', 'US', 'Orlando', 'Orlando Sanford International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (57228, 'KHR', 'ZMHH', 'MN', 'nan', 'Kharkhorin Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (54055, 'OKQ', 'WAKO', 'ID', 'Okaba-Papua Island', 'Okaba Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (11852, 'IMD', 'AYIO', 'PG', 'Imonda', 'Imonda Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (12473, 'BOK', 'BOK', 'US', 'Brookings', 'Brookings Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (53631, 'HAQ', 'VRMH', 'MV', 'Haa Dhaalu Atoll', 'Hanimaadhoo Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (15464, 'YAX', 'CKB6', 'CA', 'Angling Lake', 'Wapekeka Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (31569, 'TVC', 'KTVC', 'US', 'Traverse City', 'Cherry Capital Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (28889, 'HOB', 'KHOB', 'US', 'Hobbs', 'Lea County Regional Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (23980, 'GLK', 'HCMR', 'SO', 'Galcaio', 'Galcaio Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (23712, 'GLP', 'GLP', 'PG', 'Gulgubip', 'Gulgubip Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (23992, 'OBC', 'HDOB', 'DJ', 'Obock', 'Obock Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (38639, 'MHB', 'NZMB', 'NZ', 'Auckland City', 'Mechanics Bay Heliport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (12406, 'RHA', 'BIRE', 'IS', 'ReykhÃ³lar', 'ReykhÃ³lar Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (54536, 'OEC', 'WPOC', 'TL', 'Oecussi-Ambeno', 'Rota Do SÃ¢ndalo Oecusse Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (56405, 'RSB', 'YRSB', 'AU', 'nan', 'Roseberth Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (29058, 'IYK', 'KIYK', 'US', 'Inyokern', 'Inyokern Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (55639, 'GBL', 'YGBI', 'AU', 'nan', 'South Goulburn Is Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (29280, 'LUL', 'KLUL', 'US', 'Laurel', 'Hesler Noble Field');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (55750, 'HTU', 'YHPN', 'AU', 'nan', 'Hopetoun Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (32761, 'BVE', 'LFSL', 'FR', 'Brive la Gaillarde', 'Brive-Souillac');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (32694, 'POX', 'LFPT', 'FR', 'Cormeilles-en-Vexin', 'AÃ©rodrome de Pontoise - Cormeilles en Vexin');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (31197, 'ROA', 'KROA', 'US', 'Roanoke', 'RoanokeâBlacksburg Regional Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (21265, 'OUR', 'FKKI', 'CM', 'Batouri', 'Batouri Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (18621, 'KOQ', 'EDCK', 'DE', 'KÃ¶then', 'KÃ¶then Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (18691, 'EIB', 'EDGE', 'DE', 'Eisenach', 'Eisenach-Kindel Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (42692, 'CUT', 'SAZW', 'AR', 'Cutral-Co', 'Cutral-Co Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (47570, 'SQT', 'SQT', 'PG', 'Samarai Island', 'China Strait Airstrip');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (34755, 'CEN', 'MMCN', 'MX', 'Ciudad ObregÃ³n', 'Ciudad ObregÃ³n International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (28990, 'IAG', 'KIAG', 'US', 'Niagara Falls', 'Niagara Falls International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (41725, 'IPE', 'RPMV', 'PH', 'Ipil', 'Ipil Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (56266, 'OSO', 'YOSB', 'AU', 'nan', 'Osborne Mine Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (53710, 'KKM', 'VTBH', 'TH', 'nan', 'Sa Pran Nak Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (40237, 'KUY', '', 'PG', 'Kamusi', 'Kamusi Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (56704, 'WOL', 'YWOL', 'AU', 'nan', 'Shellharbour Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (29815, 'OCE', 'KOXB', 'US', 'Ocean City', 'Ocean City Municipal Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (12180, 'ILL', 'BDH', 'US', 'Willmar', 'Willmar Municipal -John L Rice Field');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (46462, 'SRZ', 'SLET', 'BO', 'Santa Cruz', 'El Trompillo Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (17027, 'YEM', 'CYEM', 'CA', 'Manitowaning', 'Manitoulin East Municipal Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (46963, 'JCM', 'SNJB', 'BR', 'Jacobina', 'Jacobina Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (41777, 'PPS', 'RPVP', 'PH', 'Puerto Princesa City', 'Puerto Princesa Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (20476, 'PLQ', 'EYPA', 'LT', 'Palanga', 'Palanga International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (53062, 'KTI', 'VDKT', 'KH', 'Kratie', 'Kratie Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (33751, 'SMV', 'LSZS', 'CH', 'nan', 'Samedan Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (32565, 'CLY', 'LFKC', 'FR', 'Calvi/Sainte-Catherine', 'Calvi-Sainte-Catherine Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (19364, 'BEB', 'EGPL', 'GB', 'Balivanich', 'Benbecula Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (28946, 'HYS', 'KHYS', 'US', 'Hays', 'Hays Regional Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (9912, 'CHU', '9A3', 'US', 'Chuathbaluk', 'Chuathbaluk Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (53460, 'BEK', 'VIBY', 'IN', 'Bareilly', 'Bareilly Air Force Station');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (19196, 'GLO', 'EGBJ', 'GB', 'Staverton', 'Gloucestershire Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (43228, 'ZCO', 'SCQP', 'CL', 'Temuco', 'La AraucanÃ­a Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (53324, 'IXI', 'VELR', 'IN', 'Lilabari', 'North Lakhimpur Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (32184, 'ODB', 'LEBA', 'ES', 'CÃ³rdoba', 'CÃ³rdoba Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (29300, 'LXV', 'KLXV', 'US', 'Leadville', 'Lake County Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (57270, 'NKG', 'ZSNJ', 'CN', 'Nanjing', 'Nanjing Lukou Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (31739, 'WLD', 'KWLD', 'US', 'Winfield/Arkansas City', 'Strother Field');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (44709, 'FRC', 'SIMK', 'BR', 'Franca', 'Tenente Lund Pressoto Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (56119, 'MTD', 'YMSF', 'AU', 'nan', 'Mount Sanford Station Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (33828, 'AOE', 'LTBY', 'TR', 'EskiÅehir', 'Anadolu Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (24570, 'PPJ', '', 'ID', 'Jakarta', 'Pulau Panjang Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (27835, 'CON', 'KCON', 'US', 'Concord', 'Concord Municipal Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (24761, 'IUL', '', 'ID', 'Ilu-Papua Island', 'Ilu Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (27610, 'BIE', 'KBIE', 'US', 'Beatrice', 'Beatrice Municipal Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (33314, 'LNC', 'LNC', 'PG', 'nan', 'Lengbati Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (32177, 'ABC', 'LEAB', 'ES', 'Albacete', 'Albacete-Los Llanos Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (53325, 'LDA', 'VEMH', 'IN', 'Malda', 'Malda Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (44197, 'MRR', 'SEMA', 'EC', 'MacarÃ¡', 'Jose Maria Velasco Ibarra Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (31263, 'PRZ', 'KS39', 'US', 'Prineville', 'Prineville Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (39557, 'BDN', 'OPTH', 'PK', 'Badin', 'Talhar Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (57311, 'WMT', 'ZUMT', 'CN', 'Zunyi', 'Zunyi Maotai Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (52634, 'SKD', 'UTSS', 'UZ', 'Samarkand', 'Samarkand Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (42758, 'GJM', 'SBGM', 'BR', 'GuajarÃ¡-Mirim', 'GuajarÃ¡-Mirim Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (29017, 'ILE', 'KILE', 'US', 'Killeen', 'Skylark Field');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (15436, 'CKD', 'CJX', 'US', 'Crooked Creek', 'Crooked Creek Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (19727, 'NVK', 'ENNK', 'NO', 'Narvik', 'Narvik Framnes Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (29295, 'LWT', 'KLWT', 'US', 'Lewistown', 'Lewistown Municipal Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (29403, 'XMD', 'KMDS', 'US', 'Madison', 'Madison Municipal Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (50782, 'PES', 'ULPB', 'RU', 'Petrozavodsk', 'Petrozavodsk Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (17258, 'YVQ', 'CYVQ', 'CA', 'Norman Wells', 'Norman Wells Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (17513, 'ZJN', 'CZJN', 'CA', 'Swan River', 'Swan River Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (17529, 'ZSJ', 'CZSJ', 'CA', 'Sandy Lake', 'Sandy Lake Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (46335, 'LQM', 'SKLG', 'CO', 'Puerto LeguÃ­zamo', 'Caucaya Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (27880, 'CVN', 'KCVN', 'US', 'Clovis', 'Clovis Municipal Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (18290, 'ENU', 'DNEN', 'NG', 'Enegu', 'Akanu Ibiam International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (34545, 'TEA', 'MHTE', 'HN', 'Tela', 'Tela Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (28018, 'DVT', 'KDVT', 'US', 'Phoenix', 'Phoenix Deer Valley Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (26680, 'GCW', 'K1G4', 'US', 'Peach Springs', 'Grand Canyon West Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (17254, 'YCK', 'CYVL', 'CA', 'Colville Lake', 'Tommy Kochon Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (29420, 'MFV', 'KMFV', 'US', 'Melfa', 'Accomack County Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (55993, 'MBB', 'YMBL', 'AU', 'nan', 'Marble Bar Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (33787, 'GZT', 'LTAJ', 'TR', 'Gaziantep', 'Gaziantep International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (34946, 'BZA', 'MNBZ', 'NI', 'Bonanza', 'San Pedro Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (56271, 'ADL', 'YPAD', 'AU', 'Adelaide', 'Adelaide International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (17639, 'COO', 'DBBB', 'BJ', 'Cotonou', 'Cadjehoun Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (31593, 'BFG', 'KU07', 'US', 'Bullfrog', 'Bullfrog Basin Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (29206, 'LEE', 'KLEE', 'US', 'Leesburg', 'Leesburg International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (10483, 'GEF', 'AGEV', 'SB', 'Liangia', 'Geva Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (53585, 'BLR', 'VOBL', 'IN', 'Bangalore', 'Kempegowda International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (27941, 'DAY', 'KDAY', 'US', 'Dayton', 'James M Cox Dayton International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (19754, 'RYG', 'ENRY', 'NO', 'Oslo', 'Moss Airport, Rygge');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (21427, 'NLA', 'FLND', 'ZM', 'Ndola', 'Simon Mwansa Kapwepwe International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (32865, 'JSY', 'LGSO', 'GR', 'Syros Island', 'Syros Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (36994, 'TBI', 'MYCB', 'BS', 'Cat Island', 'New Bight Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (15110, 'XMP', 'CFC4', 'CA', 'Macmillan Pass', 'Macmillan Pass Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (47223, 'OBI', 'SNTI', 'BR', 'Ãbidos', 'Ãbidos Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (38246, 'HHZ', 'NTGH', 'PF', 'Hikueru Atoll', 'Hikueru Atoll Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (47134, 'PIV', 'SNPX', 'BR', 'Pirapora', 'Pirapora Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (28921, 'HTL', 'KHTL', 'US', 'Houghton Lake', 'Roscommon County - Blodgett Memorial Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (33315, 'LNF', 'LNF', 'PG', 'nan', 'Munbil Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (52495, 'NOJ', 'USRO', 'RU', 'Noyabrsk', 'Noyabrsk Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (23991, 'MHI', 'HDMO', 'DJ', 'Moucha Island', 'Moucha Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (19244, 'EOI', 'EGED', 'GB', 'Eday', 'Eday Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (57231, 'MXV', 'ZMMN', 'MN', 'MÃ¶rÃ¶n', 'MÃ¶rÃ¶n Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (54411, 'BWH', 'WMKB', 'MY', 'Butterworth', 'Butterworth Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (46342, 'MFS', 'SKMF', 'CO', 'Miraflores', 'Miraflores Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (32256, 'MAH', 'LEMH', 'ES', 'Menorca Island', 'Menorca Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (55475, 'COY', 'YCWY', 'AU', 'Coolawanyah Station', 'Coolawanyah Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (55928, 'LDC', 'YLIN', 'AU', 'Lindeman Island', 'Lindeman Island Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (35232, 'TOO', 'MRSV', 'CR', 'Coto Brus', 'San Vito De Java Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (35105, 'SYP', 'MPSA', 'PA', 'Santiago', 'Ruben Cantu Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (38816, 'LQN', 'OAQN', 'AF', 'Qala-I-Naw', 'Qala-I-Naw Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (17154, 'YOW', 'CYOW', 'CA', 'Ottawa', 'Ottawa Macdonald-Cartier International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (43835, 'QHB', 'SDPW', 'BR', 'Piracicaba', 'Piracicaba Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (37665, 'TRW', 'NGTA', 'KI', 'Tarawa', 'Bonriki International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (48347, 'CUP', 'SVCP', 'VE', 'CarÃºpano', 'General Francisco BermÃºdez Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (46382, 'SSL', 'SKSL', 'CO', 'Santa Rosalia', 'Santa Rosalia Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (54645, 'WSA', 'WSA', 'PG', 'Wasua', 'Wasua Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (55832, 'KCS', 'YKCS', 'AU', 'nan', 'Kings Creek Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (17079, 'YHZ', 'CYHZ', 'CA', 'Halifax', 'Halifax / Stanfield International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (32331, 'ZAZ', 'LEZG', 'ES', 'Zaragoza', 'Zaragoza Air Base');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (31663, 'VAD', 'KVAD', 'US', 'Valdosta', 'Moody Air Force Base');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (17062, 'YQC', 'CYHA', 'CA', 'Quaqtaq', 'Quaqtaq Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (12377, 'HVK', 'BIHK', 'IS', 'HÃ³lmavÃ­k', 'HÃ³lmavÃ­k Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (38269, 'RRR', 'NTKO', 'PF', 'nan', 'Raroia Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (46062, 'LMC', 'SK-307', 'CO', 'La Macarena', 'El Refugio/La Macarena Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (17036, 'YFB', 'CYFB', 'CA', 'Iqaluit', 'Iqaluit Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (10548, 'SOL', 'AK26', 'US', 'Solomon', 'Solomon State Field');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (56278, 'CCK', 'YPCC', 'CC', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (39926, 'KKH', 'PADY', 'US', 'Kongiganak', 'Kongiganak Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (21624, 'UEL', 'FQQL', 'MZ', 'Quelimane', 'Quelimane Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (33050, 'QPA', 'LIPU', 'IT', 'Padova', 'Padova Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (28000, 'DSV', 'KDSV', 'US', 'Dansville', 'Dansville Municipal Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (32730, 'DNR', 'LFRD', 'FR', 'Dinard/Pleurtuit/Saint-Malo', 'Dinard-Pleurtuit-Saint-Malo Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (23608, 'FLH', 'FLH', 'GB', 'Flotta Isle', 'Flotta Isle Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (53538, 'DNP', 'VNDG', 'NP', 'Dang', 'Tulsipur Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (40441, 'JHM', 'PHJH', 'US', 'Lahaina', 'Kapalua Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (54189, 'BKI', 'WBKK', 'MY', 'Kota Kinabalu', 'Kota Kinabalu International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (22359, 'KKW', 'FZCA', 'CD', 'nan', 'Kikwit Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (27787, 'CID', 'KCID', 'US', 'Cedar Rapids', 'The Eastern Iowa Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (46352, 'NQU', 'SKNQ', 'CO', 'NuquÃ­', 'Reyes Murillo Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (53297, 'RGH', 'VEBG', 'IN', 'Balurghat', 'Balurghat Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (17295, 'YYF', 'CYYF', 'CA', 'Penticton', 'Penticton Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (56418, 'RHL', 'YRYH', 'AU', 'nan', 'Roy Hill Station Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (50557, 'OYG', 'OYG', 'UG', 'Moyo', 'Moyo Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (4105, 'BYW', '38WA', 'US', 'Blakely Island', 'Blakely Island Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (19734, 'HOV', 'ENOV', 'NO', 'Ãrsta', 'Ãrsta-Volda Airport, Hovden');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (54007, 'UPG', 'WAAA', 'ID', 'Ujung Pandang-Celebes Island', 'Hasanuddin International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (39516, 'LHE', 'OPLA', 'PK', 'Lahore', 'Alama Iqbal International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (41141, 'PIF', 'RCSQ', 'TW', 'Pingtung', 'Pingtung North Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (23767, 'DKR', 'GOOY', 'SN', 'Dakar', 'LÃ©opold SÃ©dar Senghor International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (39528, 'MUX', 'OPMT', 'PK', 'Multan', 'Multan International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (12003, 'WWK', 'AYWK', 'PG', 'Wewak', 'Wewak International Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (49637, 'FAJ', 'TJFA', 'PR', 'Fajardo', 'Diego Jimenez Torres Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (37617, 'RBI', 'NFFR', 'FJ', 'Rabi Island', 'Rabi Island Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (49951, 'MQS', 'TVSM', 'VC', 'Mustique Island', 'Mustique Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (42812, 'PMW', 'SBPJ', 'BR', 'Palmas', 'Brigadeiro Lysias Rodrigues Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (20324, 'GVX', 'ESSK', 'SE', 'GÃ¤vle / Sandviken', 'GÃ¤vle Sandviken Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (43288, 'ZIC', 'SCTO', 'CL', 'Victoria', 'Victoria Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (56485, 'HLS', 'YSTH', 'AU', 'nan', 'St Helens Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (55484, 'DNB', 'YDBR', 'AU', 'nan', 'Dunbar Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (42636, 'LHS', 'SAVH', 'AR', 'Las Heras', 'Las Heras Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (12403, 'NOR', 'BINF', 'IS', 'NorÃ°fjÃ¶rÃ°ur', 'NorÃ°fjÃ¶rÃ°ur Airport');
insert into airports (id, code_iata, code_icao, country, municipality, name) values (20630, 'ASS', 'FACC', 'ZA', 'Arathusa', 'Arathusa Safari Lodge Airport');
